%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\lab\dual-comb-ptychoscopy\0204\comb1.Wfm.csv
%
% Auto-generated by MATLAB on 04-Feb-2026 22:44:28

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("./interfer2.Wfm.csv", opts);

data = table2array(data);

clear opts

t = data(:,1);
s = data(:,2);

%% 1. Define Sampling Parameters
dt = t(2) - t(1);           % Time step
fs = 1/dt;                  % Sampling frequency
L = length(s);              % Length of signal
f = (0:(L/2)) * (fs/L);     % Frequency vector
T = L * dt;
df = 1 / T;

%% 2. Perform FFT
% Compute the two-sided spectrum P2. 
% Then compute the single-sided spectrum P1 based on P2 and the signal length L.
Y = fft(s);
P2 = abs(Y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2*P1(2:end-1);
eps = 0;
P1_dB = 20*log10(P1 + eps); % Magnitude in dB

%% 2. Plot with Linear Frequency Axis (Stawdard for RF/Comb)
figure;
plot(f / 1e9, P1_dB, 'LineWidth', 1.5) % Plot f in GHz directly
xlabel('Frequency (GHz)')
ylabel('Magnitude (dB)')
xlim([0, 6]) 
set(gca, "Fontsize", 18)
grid on