%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\My Drive\lab\telecomb_dual_comb_chip\dual-comb-ptychoscopy\beatnote.Wfm.csv
%
% Auto-generated by MATLAB on 19-Mar-2026 21:48:36

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "Var1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("G:\My Drive\lab\telecomb_dual_comb_chip\dual-comb-ptychoscopy\beatnote.Wfm.csv", opts);

%% Convert to output type
data = table2array(data);

%% Clear temporary variables
clear opts

L = length(data);
dt = 1e-9;
Fs = 1/ dt;
f = (0:(L/2)) * (Fs/L);
Y = fft(data);
Y = Y(1:L/2+1);
P = abs(Y/L);
P(2:end-1) = 2*P(2:end-1);
P = 20*log10(P); 
figure;
plot(f/1e6, P, 'LineWidth', 1.5);